name = "lawlanes-nextjs-app"
compatibility_date = "2024-07-25"

[build]
command = "npm run build"

[dev]
port = 3000

# Next.js requires the `nodejs_compat` compatibility flag.
# See https://developers.cloudflare.com/workers/runtime-apis/nodejs/
[[compatibility_flags]]
name = "nodejs_compat"
